version: '3.7'

services:
  academy-preview:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: localhost:5000/lennelearning:prod
    restart: unless-stopped
    container_name: lennelearning-prod
    networks:
      - traefik-public
    entrypoint: ['/bin/sh', '-c']
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.lennelearning-prod-app-http.rule=Host(`lennelearning.de`, `www.lennelearning.de`)
        - traefik.http.routers.lennelearning-prod-app-http.entrypoints=http
        - traefik.http.routers.lennelearning-prod-app-http.middlewares=https-redirect
        - traefik.http.routers.lennelearning-prod-app-https.rule=Host(`lennelearning.de`, `www.lennelearning.de`)
        - traefik.http.routers.lennelearning-prod-app-https.entrypoints=https
        - traefik.http.routers.lennelearning-prod-app-https.tls=true
        - traefik.http.routers.lennelearning-prod-app-https.tls.certresolver=le
        - traefik.http.middlewares.lennelearning-prod-redirect.redirectregex.regex=^https?://www.lennelearning.de/(.*)
        - traefik.http.middlewares.lennelearning-prod-redirect.redirectregex.replacement=https://lennelearning.de/$${1}
        - traefik.http.middlewares.lennelearning-prod-redirect.redirectregex.permanent=true
        - traefik.http.services.lennelearning-prod-app.loadbalancer.server.port=4000
        - traefik.http.routers.lennelearning-prod-app-https.middlewares=lennelearning-prod-redirect
    command:
      - |
        NODE_ENV="production" SMTP_USER=${SMTP_USER} SMTP_PW=${SMTP_PW} npx node main.js

volumes:
  node_modules:

networks:
  traefik-public:
    external: true
