FROM mhart/alpine-node:16

RUN mkdir -p /var/www/

RUN apk --no-cache add curl

COPY ./dist/academy ./var/www

HEALTHCHECK --interval=60s --retries=5 CMD curl --fail http://localhost:4000/ || exit 1

WORKDIR /var/www/server

EXPOSE 4000
