name: Build

on:
  pull_request:
    branches-ignore:
      - 'test'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.17
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Install
        run: npm install
      - name: Build app
        run: npm run build:ssr
