name: Deploy

on:
  release:
    types:
      - released

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.17
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Install
        run: npm install
      - name: Build app
        run: npm run build:ssr
      - name: Build docker
        run: docker-compose -f docker-compose.prod.yml build
      - name: Push docker
        run: docker-compose -f docker-compose.prod.yml push
      - name: Deploy
        run: docker stack deploy -c docker-compose.prod.yml --with-registry-auth academy-prod
      - name: Deploy notification
        if: always()
        uses: adamkdean/simple-slack-notify@master
        with:
          channel: '#akademie-tutoren'
          status: ${{ job.status }}
          success_text: 'Version (#${{github.event.release.tag_name}}) der Akademie wurde erfolgreich released.'
          failure_text: 'Release (#${{github.event.release.tag_name}}) failed'
          cancelled_text: 'Release (#${{github.event.release.tag_name}}) was cancelled'
