name: Deploy

on:
  release:
    types:
      - released

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PW: ${{ secrets.SMTP_PW }}

jobs:
  deploy:
    runs-on: [self-hosted, docker-live]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install
        run: npm install
      - name: Build app
        run: npm run build:ssr
      - name: Build docker
        run: SMTP_USER=$SMTP_USER SMTP_PW=$SMTP_PW docker-compose -f docker-compose.prod.yml build
      - name: Push docker
        run: SMTP_USER=$SMTP_USER SMTP_PW=$SMTP_PW docker-compose -f docker-compose.prod.yml push
      - name: Deploy
        run: SMTP_USER=$SMTP_USER SMTP_PW=$SMTP_PW docker stack deploy -c docker-compose.prod.yml --with-registry-auth lennelearning-prod
      - name: Deploy notification
        if: always()
        uses: adamkdean/simple-slack-notify@master
        with:
          channel: '#akademie-tutoren'
          status: ${{ job.status }}
          success_text: 'Version (#${{github.event.release.tag_name}}) von lenne.learning wurde erfolgreich released.'
          failure_text: 'Release (#${{github.event.release.tag_name}}) failed'
          cancelled_text: 'Release (#${{github.event.release.tag_name}}) was cancelled'
